### ISSUE TITLE
'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Acidhub** [ShyPixie/steam-tools-ng#14]
![image](https://user-images.githubusercontent.com/5482388/49117216-1a447180-f287-11e8-82ad-0ef038bfe1b4.png)

steam-tools-ng:INFO => Steam Tools NG version 0.7.2.rc3 (Made with Girl Power <33)
steam-tools-ng:INFO => Copyright (C) 2015 ~ 2018 Lara Maia - <dev@lara.click>
plugins:DEBUG => Plugin steamgifts registered.
plugins:DEBUG => Plugin steamtrades registered.
plugins:DEBUG => Unable to find plugin directory in:
C:\Users\manfr\AppData\Local\stlib\plugins
webapi:DEBUG => login status code: 200
webapi:DEBUG => Requesting ISteamWebAPIUtil:GetServerInfo via GET with {}:None
client:DEBUG => Set SteamAppId to 480
client:DEBUG => server init returns True
client:DEBUG => Closing GameServer
client:DEBUG => Set SteamAppId to 321400
client:DEBUG => SteamAPI init returns True
webapi:DEBUG => server time found: 1543355267
base_events:ERROR => SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000000090b1a58>
transport: <_ProactorSocketTransport fd=1516 read=<_OverlappedFuture pending overlapped=<pending, 0x91163a0> cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "E:\msys2_64\mingw64\lib\python3.7\asyncio\sslproto.py", line 526, in data_received
  File "E:\msys2_64\mingw64\lib\python3.7\asyncio\sslproto.py", line 207, in feed_ssldata
  File "E:\msys2_64\mingw64\lib\python3.7\ssl.py", line 767, in unwrap
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2592)
application:DEBUG => Ignorando atualização das confirmações porque os dados não parecem ter mudado
client:DEBUG => Set SteamAppId to 480
client:DEBUG => server init returns True
client:DEBUG => Closing GameServer
webapi:DEBUG => Requesting ISteamWebAPIUtil:GetServerInfo via GET with {}:None
webapi:DEBUG => server time found: 1543355285
application:DEBUG => Ignorando atualização das confirmações porque os dados não parecem ter mudado

(...)

client:DEBUG => Set SteamAppId to 480
client:DEBUG => server init returns True
client:DEBUG => Closing GameServer
webapi:DEBUG => Requesting ISteamWebAPIUtil:GetServerInfo via GET with {}:None
webapi:DEBUG => server time found: 1543358117
application:DEBUG => Ignorando atualização das confirmações porque os dados não parecem ter mudado
application:CRITICAL => AttributeError("'NoneType' object has no attribute 'find'")

**Comment by ShyPixie** [comment]
Please, check if it has been fixed on version 0.8

If not, send the log again.

**Comment by Acidhub** [comment]
Fixed #14
Works fine now. 👍
