### ISSUE TITLE
Unrefined translation ready to be added

### ISSUE THREAD

**Issue by Zorrototo** [ShyPixie/steam-tools-ng#22]
I made the FR translation tonight, in case you didn't see. It is ready to be tested if you can add it I'll be able to see if I made mistake or if it needs adjustments. https://www.transifex.com/steam-tools-ng/steam-tools-ng/language/fr/

**Comment by ShyPixie** [comment]
Sorry for delay, I'm spending time away from the internet
This is fixed by 8b4e4d2785d50e3fec19b1471b131cce7539d1ab

**Comment by Zorrototo** [comment]
I translated the rest it should be complete, it now needs inspection in the tool itself, I have a limited test case with my account as It is restricted regarding most of Steam functionalities, so I will not be able to test everything.

**Comment by Zorrototo** [comment]
So far it seems to be all good.

I noticed you added credits for FR translation, thanks, but my name is "®omano" not "mano" :P
