### ISSUE TITLE
Found bug in (French translation) v0.9.3

### ISSUE THREAD

**Issue by Zorrototo** [ShyPixie/steam-tools-ng#23]
Start the tool, select using 'SECRETS' in the Magic Box, enter valid account info, but enter bogus secrets (abc/def for instance in my test), and validate, it creates a fatal error with message:

> CECI EST UNE ERREUR FATALE!!! VEUILLEZ LA RAPPORTER!!!
> 
> Error('Incorrect padding')

**Comment by ShyPixie** [comment]
It's occurring because you enter invalid secrets

**Comment by ShyPixie** [comment]
Fixed at stlib
